blank_issues_enabled: true
contact_links:
  - name: Mallior Core Security Policy
    url: https://github.com/mallior/mallior/blob/master/SECURITY.md
    about: View security policy
  - name: Mallior Core Developers
    url: https://bitcoincore.org
    about: Mallior Core homepage
